create database solution7;
use solution7;

CREATE EXTERNAL TABLE EMPLOYEE7 (EMP_NO INT,
BIRTH_DATE STRING,
FIRST_NAME STRING,
LAST_NAME STRING,
GENDER STRING,
HIRE_DATE STRING)
PARTITIONED BY (HIRE_YEAR STRING,HIRE_MONTH STRING)
LOCATION '/user/cloudera/solution7';

set hive.exec.dynamic.partition.mode=nonstrict
set hive.exec.max.dynamic.partitions.pernode = 1000;

INSERT OVERWRITE TABLE EMPLOYEE7 PARTITION(HIRE_YEAR,HIRE_MONTH)
SELECT EMP_NO,BIRTH_DATE,FIRST_NAME,LAST_NAME,GENDER,HIRE_DATE,
SPLIT(HIRE_DATE,"-")[0] AS HIRE_YEAR,SPLIT(HIRE_DATE,"-")[1] AS HIRE_MONTH FROM DEFAULT.EMPLOYEES;
